### ISSUE TITLE
Error findup-sync not found with grunt-cli 0.1.13

### ISSUE THREAD

**Issue by ManasaVTR** [gruntjs/grunt-docs#223]
We have been working with grunt-cli version 0.1.13 , node version - 6.17.1, npm version-3.10.10
While running grunt commands we are seeing dependency not  found errors  even though these modules are present in node_modules.
Can anyone help us resolving this issue ?
Error while running grunt --help
Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\6110853\AppData\Roaming\nvm\v6.17.1\node_modules\grunt-cli\bin\grunt:8:14)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

**Comment by vladikoff** [comment]
@ManasaVTR, your node js version seems very old

node version - 6.17.1 is that right?

LTS is now at version 18

**Comment by ManasaVTR** [comment]
Yes . We haven't updated node version a few of the dependencies might break .
Do you think updating node version can resolve the issue with grunct-cli ?

**Comment by ManasaVTR** [comment]
After increasing Node Js to 17.0.0 I am getting the below error :
> grunt --version
grunt-cli v1.4.3
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'getobject'
Require stack:
- C:\workspace\ui\ri-desktop_accelus-ri-app\ui\node_modules\grunt-legacy-util\index.js
- C:\workspace\ui\ri-desktop_accelus-ri-app\ui\node_modules\grunt\lib\grunt.js
- C:\Users\6110853\AppData\Roaming\nvm\v17.0.0\node_modules\grunt-cli\bin\grunt
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\workspace\ui\ri-desktop_accelus-ri-app\ui\node_modules\grunt-legacy-util\index.js:20:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\workspace\\ui\\ri-desktop_accelus-ri-app\\ui\\node_modules\\grunt-legacy-util\\index.js',
    'C:\\workspace\\ui\\ri-desktop_accelus-ri-app\\ui\\node_modules\\grunt\\lib\\grunt.js',
    'C:\\Users\\6110853\\AppData\\Roaming\\nvm\\v17.0.0\\node_modules\\grunt-cli\\bin\\grunt'
  ]
}

Node.js v17.0.0

**Comment by ManasaVTR** [comment]
With node version 8


PS C:\workspace\ui\ri-desktop_accelus-ri-app\ui> grunt --version
C:\Users\6110853\AppData\Roaming\nvm\v8.2.0\node_modules\grunt-cli\node_modules\micromatch\index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\6110853\AppData\Roaming\nvm\v8.2.0\node_modules\grunt-cli\node_modules\findup-sync\index.js:12:10)
